
services:
  app:
    build:
      context: .
      dockerfile: Dockerfile
    container_name: todo-api
    ports:
      - "3000:3000"
    environment:
      DATABASE_URL: "postgresql://postgres:postgres@db:5432/tododb?connect_timeout=5&statement_timeout=5000"
      PORT: "3000"
    depends_on:
      db:
        condition: service_healthy
    command: >
      sh -c "npx prisma migrate deploy && npm start"
    networks:
      - keploy-network

  db:
    image: postgres:18-alpine
    container_name: postgres-todo-db
    restart: always
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: postgres
      POSTGRES_DB: tododb
    ports:
      - "5432:5432"
    volumes:
      - postgres_data:/var/lib/postgresql/data
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U postgres -d tododb"]
      interval: 5s
      timeout: 5s
      retries: 5
    networks:
      - keploy-network

networks:
  keploy-network:
    external: true

volumes:
  postgres_data:
